export function formatUgx(amount) {
  if (typeof amount === 'string' && amount.startsWith('UGX')) return amount
  return `UGX ${Number(amount).toLocaleString('en-UG')}`
}

export const websitePackages = [
  {
    id: 'starter',
    emoji: '🟢',
    title: 'Starter Web',
    priceUgx: 250000,
    idealFor: 'Students, hustlers, small traders',
    pages: '5–10',
    features: [
      'Mobile friendly design',
      'WhatsApp chat button',
      'Business contact info',
      'Basic Google visibility setup',
      'Free .ug domain (optional)',
      'Free support for 14 days',
    ],
    highlight: 'Start strong with an online presence at the lowest cost',
    cta: '/portfolio-app/order',
  },
  {
    id: 'business-basic',
    emoji: '🔵',
    title: 'Business Basic',
    priceUgx: 400000,
    idealFor: 'Small businesses, startups',
    pages: '10–25',
    features: [
      'Mobile responsive layout',
      'About, Services, Contact, Gallery pages',
      'Contact form & WhatsApp link',
      'Social media integration',
      'Google-friendly structure',
      'Hosting setup included',
    ],
    highlight: 'Make your business searchable, reachable & professional',
    badge: 'popular',
    cta: '/portfolio-app/order',
  },
  {
    id: 'standard-growth',
    emoji: '🟣',
    title: 'Standard Growth',
    priceUgx: 850000,
    idealFor: 'SMEs, NGOs, schools, clinics',
    pages: '6–10',
    features: [
      'Mobile-first responsive design',
      'Admin Dashboard / CMS',
      'Blog or News section',
      'Google SEO boost',
      'SSL security',
      'Embedded maps, social feeds, sliders',
    ],
    highlight: 'A complete digital growth tool for small–mid organizations',
    cta: '/portfolio-app/order',
  },
  {
    id: 'pro-ecommerce',
    emoji: '🔴',
    title: 'Pro E-Commerce',
    priceUgx: 2500000,
    idealFor: 'Online shops, boutiques, tech sellers',
    pages: '10–20',
    features: [
      'Responsive online store design',
      'Shopping cart, checkout, categories',
      'Mobile Money (MoMo/Airtel) integration',
      'Admin dashboard for orders, stock, users',
      'Email alerts + SSL security',
      'Product search + filters',
    ],
    highlight: 'Launch your shop online and start selling 24/7',
    cta: '/portfolio-app/order',
  },
  {
    id: 'custom-web',
    emoji: '🟡',
    title: 'Custom Web Apps',
    priceLabel: 'From UGX 3,500,000',
    idealFor: 'SACCOs, schools, dashboards, internal tools',
    pages: 'Custom',
    features: [
      'Web system with custom dashboards',
      'Role-based login & authentication',
      'Form submissions & user profiles',
      'Reporting, data export, analytics',
      'API integrations (e.g. MoMo)',
      'Built for performance & security',
    ],
    highlight: 'Digitize your operations with a tailor-made smart web system',
    cta: '/#contact',
  },
]

export const appPackages = [
  {
    id: 'ecommerce-app',
    emoji: '🛍️',
    title: 'E-Commerce App',
    priceLabel: 'From UGX 2,500,000',
    idealFor: 'Shops, fashion stores, electronics dealers',
    features: [
      'Product listings & search',
      'Shopping cart + checkout',
      'Mobile Money integration',
      'Admin dashboard',
      'Order management',
      'Push/email notifications',
    ],
    highlight: 'Launch a full-featured online store that sells 24/7',
    cta: '/#contact',
  },
  {
    id: 'restaurant-app',
    emoji: '🍔',
    title: 'Restaurant & Delivery App',
    priceLabel: 'From UGX 3,500,000',
    idealFor: 'Restaurants, cafes, takeaways, food couriers',
    features: [
      'Menu browsing',
      'Order placement + cart',
      'Rider/driver panel (optional)',
      'Real-time status updates',
      'MoMo/AirtelPay checkout',
      'Admin dashboard',
    ],
    highlight: 'Serve meals faster with a branded digital ordering system',
    cta: '/#contact',
  },
  {
    id: 'sacco-app',
    emoji: '🏦',
    title: 'SACCO / Finance System',
    priceLabel: 'From UGX 4,000,000',
    idealFor: 'SACCOs, microfinance firms, co-ops',
    features: [
      'Member registration & loans',
      'Transactions & balances',
      'MoMo integration (optional)',
      'Staff/admin dashboard',
      'Reports, analytics & downloads',
      'Secure authentication',
    ],
    highlight: 'Digitize SACCO operations securely & professionally',
    cta: '/#contact',
  },
  {
    id: 'school-app',
    emoji: '🏫',
    title: 'School Management App',
    priceLabel: 'From UGX 3,800,000',
    idealFor: 'Private schools, colleges, training centers',
    features: [
      'Student enrollment & records',
      'Class schedules',
      'Staff/teacher panels',
      'Fees tracking + invoices',
      'Reports & result slips',
      'MoMo payment options',
    ],
    highlight: 'Streamline school admin and connect better with students',
    cta: '/#contact',
  },
  {
    id: 'inventory-pos',
    emoji: '📦',
    title: 'Inventory & POS App',
    priceLabel: 'From UGX 2,800,000',
    idealFor: 'Shops, pharmacies, wholesalers',
    features: [
      'Product tracking',
      'Stock level alerts',
      'Barcode/QR scanning',
      'Sales dashboard',
      'Receipts & reporting',
      'Staff access control',
    ],
    highlight: 'Track sales and stock with a custom digital cash register',
    cta: '/#contact',
  },
  {
    id: 'custom-app',
    emoji: '🧩',
    title: 'Custom System',
    priceLabel: 'Quote only',
    idealFor: 'Any specialized app or tool',
    features: [
      'Built 100% to your needs',
      'Business workflows for any industry',
      'API integrations',
      'Role management',
      'Fully scalable & secure',
    ],
    highlight: "Let's build exactly what your business needs — no limits",
    cta: '/#contact',
  },
]

export const aboutStats = [
  { icon: '😊', value: '232+', label: 'Happy clients' },
  { icon: '📁', value: '521+', label: 'Projects delivered' },
  { icon: '🎧', value: '1,463+', label: 'Hours of support' },
  { icon: '👥', value: '13', label: 'Team members' },
]
